
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.betteranimalsplus]
		enable_compat_betteranimalsplus = true

