#Any level of feather falling prevents farmland being trampled.
no_farmland_trample = true
#Looting also affects dropped experience points.
looting_boosts_xp = true
#Infinity enchantment no longer requires a single arrow to be present in the player inventory.
true_infinity = true
#Mending no longer repairs items using xp.
#Instead mending allows the item to be repaired in the crafting menu in the same way as in an anvil without any experience cost: combining a tool with another one or the appropriate repair item is possible, all enchantments will be preserved (but no new ones from the item repaired with will be added as an anvil would do).
#Additionally, repairing items enchanted with mending (only repairing, no renaming or adding more enchantments) in an anvil doesn't increase the items repair cost any further.
mending_crafting_repair = false
#Disables damage immunity when hit by a projectile. Makes it possible for entities to be hit by multiple projectiles at once (mainly useful for the multishot enchantment).
no_projectile_immunity = true
#Remove the max level cap from the /enchant command, also allow overriding and removing (by setting the level to 0) existing enchantment levels.
#Additionally make enchanting books work via the command.
fix_enchant_command = true
#Enchanting a few modded items (e.g. Farmer's Delight's skillet) is broken by the changes this mod makes to how enchantments may be applied to items. This option enables a patch for Forge itself to help better support such items.
allow_mod_item_support = false

